version: '3'
services:
 db:
  image: postgres
  restart: always
  environment:
  - POSTGRES_PASSWORD=postgrespasswd
  - POSTGRES_USER=postgres
  ports:
  - 5432:5432
  volumes:
    - /tank1/postgresql-data:/var/lib/postgresql/data
    - /etc/localtime:/etc/localtime